---
# tasks file for db
- name: Change mongo config file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644 # права на файл, которые нужно установить
  notify: restart mongod
